name: Deploy to Replicate

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cog
        run: |
          sudo curl -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64 -o /usr/local/bin/cog
          sudo chmod +x /usr/local/bin/cog

      - name: Login to Replicate
        env:
          TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          echo "$TOKEN" | cog login --token-stdin

      - name: Deploy model
        run: |
          cog push r8.im/selajuf/face-shape-classifier
